spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=10000&socketTimeout=30000
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
logging.level.org.springframework.security=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=urvi.ghorpade7@gmail.com
spring.mail.password=zozu aklf gpuw fqnl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=RealEstateLeadManagerSecretKeyForJWT2026Secure